// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"

#include "nvs.h"
#include "nvs_flash.h"
#include "ui_events.h"
#include "ui_helpers.h"

#define KEY_FOCUS_TIME "focus"
#define KEY_BREAK_TIME "break"

extern lv_indev_t *enc_indev;
extern lv_indev_drv_t enc_drv;
extern lv_group_t *group_obj[2];

extern int focus_time;
extern int break_time;
extern bool start_focus;

void saveValue(const char *key, int32_t val);
int loadValue(const char *key);
void set_custom_label_text(lv_obj_t *label, int val);

// SCREEN: ui_MainScreen__
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen(lv_event_t *e);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_labelMinuts;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_labelColon;
extern lv_obj_t *ui_labelSeconds;
extern lv_obj_t *ui_labelFocus;
// CUSTOM VARIABLES

// SCREEN: ui_ConfScreen
void ui_ConfScreen_screen_init(void);
void ui_event_ConfScreen(lv_event_t *e);
void ui_event_labelMinConf(lv_event_t *e);
void ui_event_labelSessionsConf(lv_event_t *e);
extern lv_obj_t *ui_ConfScreen;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_labelMinConf;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_labelConfBreakTime;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Mons110);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
