// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ConfScreen_screen_init(void) {
  ui_ConfScreen = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_ConfScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_add_flag(ui_ConfScreen, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_set_style_bg_color(ui_ConfScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ConfScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label1 = lv_label_create(ui_ConfScreen);
  lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_Label1, -1);
  lv_obj_set_y(ui_Label1, -90);
  lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label1, "Focus config");
  lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelMinConf = lv_label_create(ui_ConfScreen);
  lv_obj_set_width(ui_labelMinConf, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelMinConf, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelMinConf, -30);
  lv_obj_set_y(ui_labelMinConf, -14);
  lv_obj_set_align(ui_labelMinConf, LV_ALIGN_CENTER);
  set_custom_label_text(ui_labelMinConf, focus_time);
  lv_obj_add_flag(ui_labelMinConf, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_set_style_text_color(
      ui_labelMinConf, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelMinConf, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_labelMinConf, &ui_font_Mons110, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_color(
      ui_labelMinConf, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
  lv_obj_set_style_text_opa(ui_labelMinConf, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

  ui_Label5 = lv_label_create(ui_ConfScreen);
  lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_Label5, 66);
  lv_obj_set_y(ui_Label5, 11);
  lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label5, "min");
  lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label6 = lv_label_create(ui_ConfScreen);
  lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_Label6, 20);
  lv_obj_set_y(ui_Label6, 68);
  lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label6, "break");
  lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelConfBreakTime = lv_label_create(ui_ConfScreen);
  lv_obj_set_width(ui_labelConfBreakTime, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_labelConfBreakTime, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_labelConfBreakTime, -53);
  lv_obj_set_y(ui_labelConfBreakTime, 63);
  lv_obj_set_align(ui_labelConfBreakTime, LV_ALIGN_CENTER);
  set_custom_label_text(ui_labelConfBreakTime, break_time);
  lv_obj_add_flag(ui_labelConfBreakTime, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_set_style_text_color(
      ui_labelConfBreakTime, lv_color_hex(0x878585), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelConfBreakTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(
      ui_labelConfBreakTime, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_color(
      ui_labelConfBreakTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
  lv_obj_set_style_text_opa(ui_labelConfBreakTime, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

  lv_obj_add_event_cb(ui_ConfScreen, ui_event_ConfScreen, LV_EVENT_ALL, NULL);

  lv_obj_add_event_cb(ui_labelMinConf, ui_event_labelMinConf, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_labelConfBreakTime, ui_event_labelSessionsConf, LV_EVENT_ALL, NULL);
}
