// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void) {
  ui_Screen1 = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label1 = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_Label1, -2);
  lv_obj_set_y(ui_Label1, -3);
  lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label1, "30");
  lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Arc1 = lv_arc_create(ui_Screen1);
  lv_obj_set_width(ui_Arc1, 219);
  lv_obj_set_height(ui_Arc1, 279);
  lv_obj_set_x(ui_Arc1, 0);
  lv_obj_set_y(ui_Arc1, 29);
  lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
  lv_arc_set_value(ui_Arc1, 50);
}
